NAME: Naveen Goyal, ROLL NO: 102303757

In [ ]:
#Q1: Questions on Basic NumPy Array 
#(a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5]) 
import numpy as np
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed Array:", reversed_arr)


Reversed Array: [5 4 6 3 2 1]


In [ ]:
#(b) Flatten the NumPy arr: array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]]) using any twoNumPy in-built methods 
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
flat1 = array1.flatten()
flat2 = array1.ravel()
print("Flatten (flatten):", flat1)
print("Flatten (ravel):", flat2)


Flatten (flatten): [1 2 3 2 4 5 1 2 3]
Flatten (ravel): [1 2 3 2 4 5 1 2 3]


In [ ]:
#(c) Compare the following numpy arrays:
#arr1 = np.array([[1, 2], [3, 4]])
# #arr2 = np.array([[1, 2], [3, 4]])
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

print("Are arrays equal (element-wise)?\n", arr1 == arr2)
print("Are arrays identical (allclose)?", np.array_equal(arr1, arr2))


Are arrays equal (element-wise)?
 [[ True  True]
 [ True  True]]
Are arrays identical (allclose)? True


In [ ]:
#(d) Find the most frequent value and their indice(s) in the following arrays:
#i. x = np.array([1,2,3,4,5,1,2,1,1,1])
#ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]) 
def most_frequent_with_indices(arr):
    values, counts = np.unique(arr, return_counts=True)
    max_count_idx = np.argmax(counts)
    most_freq = values[max_count_idx]
    indices = np.where(arr == most_freq)[0]
    return most_freq, indices

x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

print("x:", most_frequent_with_indices(x))
print("y:", most_frequent_with_indices(y))


x: (1, array([0, 5, 7, 8, 9], dtype=int64))
y: (1, array([0, 1, 2], dtype=int64))


In [ ]:
#(e) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'), find
#i. Sum of all elements
#ii. Sum of all elements row-wise
#iii. Sum of all elements column-wise
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("Sum all elements:", np.sum(gfg))
print("Sum row-wise:", np.sum(gfg, axis=1))
print("Sum col-wise:", np.sum(gfg, axis=0))


Sum all elements: 45
Sum row-wise: [[14]
 [16]
 [15]]
Sum col-wise: [[20  9 16]]


In [ ]:
#(f) For the matrix: n_array = np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]]), find
#i. Sum of diagonal elements
#ii. Eigen values of matrix
#iii. Eigen vectors of matrix
#iv. Inverse of matrix
#v. Determinant of matrix 
n_array = np.array([
    [55, 25, 15],
    [30, 44, 2],
    [11, 45, 77]
])

print("Diagonal sum:", np.trace(n_array))
eigen_values, eigen_vectors = np.linalg.eig(n_array)
print("Eigenvalues:", eigen_values)
print("Eigenvectors:\n", eigen_vectors)
inv = np.linalg.inv(n_array)
print("Inverse matrix:\n", inv)
det = np.linalg.det(n_array)
print("Determinant:", det)


Diagonal sum: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse matrix:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [ ]:
#(g) Multiply the following matrices and also find covariance between matrices using NumPy:
#i. p = [[1, 2], [2, 3]]
#q = [[4, 5], [6, 7]]
#ii. p = [[1, 2], [2, 3], [4, 5]]
#q = [[4, 5, 1], [6, 7, 2]]
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
product1 = np.dot(p1, q1)
print("Product 1:\n", product1)
print("Covariance (flattened):\n", np.cov(p1.ravel(), q1.ravel()))
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
product2 = np.dot(p2, q2)
print("Product 2:\n", product2)
print("Covariance (flattened):\n", np.cov(p2.ravel(), q2.ravel()))


Product 1:
 [[16 19]
 [26 31]]
Covariance (flattened):
 [[0.66666667 1.        ]
 [1.         1.66666667]]
Product 2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]
Covariance (flattened):
 [[2.16666667 0.23333333]
 [0.23333333 5.36666667]]


In [ ]:
#(h) For the matrices: x = np.array([[2, 3, 4], [3, 2, 9]]); y = np.array([[1, 5, 0], [5, 10, 3]]),
#find inner, outer and cartesian product?
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner product
print("Inner product:\n", np.inner(x, y))
# Outer product
print("Outer product:\n", np.outer(x.ravel(), y.ravel()))
# Cartesian product (pairs)
from itertools import product
cartesian_prod = np.array(list(product(x.flatten(), y.flatten())))
print("Cartesian product:\n", cartesian_prod)


Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


In [ ]:
#Q2: Based on NumPy Mathematics and Statistics
#(a) For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
#i. Find element-wise absolute value
#ii. Find the 25th, 50th, and 75th percentile of flattened array, for each column, for each
#row.
#iii. Mean, Median and Standard Deviation of flattened array, of each column, and
#each row 
array = np.array([[1, -2, 3],[-4, 5, -6]])

# i. Absolute values
print("Absolute:\n", np.abs(array))

# ii. Percentiles
flattened = array.flatten()
print("Percentile (flattened):", [np.percentile(flattened, p) for p in [25, 50, 75]])
print("Percentile (columns):", [np.percentile(array[:,i], [25, 50, 75]) for i in range(array.shape[1])])
print("Percentile (rows):", [np.percentile(array[i], [25, 50, 75]) for i in range(array.shape[0])])

# iii. Mean, Median, Stddev
print("Mean (flattened):", np.mean(flattened))
print("Mean (columns):", np.mean(array, axis=0))
print("Mean (rows):", np.mean(array, axis=1))
print("Median (flattened):", np.median(flattened))
print("Median (columns):", np.median(array, axis=0))
print("Median (rows):", np.median(array, axis=1))
print("Std (flattened):", np.std(flattened))
print("Std (columns):", np.std(array, axis=0))
print("Std (rows):", np.std(array, axis=1))


Absolute:
 [[1 2 3]
 [4 5 6]]
Percentile (flattened): [-3.5, -0.5, 2.5]
Percentile (columns): [array([-2.75, -1.5 , -0.25]), array([-0.25,  1.5 ,  3.25]), array([-3.75, -1.5 ,  0.75])]
Percentile (rows): [array([-0.5,  1. ,  2. ]), array([-5. , -4. ,  0.5])]
Mean (flattened): -0.5
Mean (columns): [-1.5  1.5 -1.5]
Mean (rows): [ 0.66666667 -1.66666667]
Median (flattened): -0.5
Median (columns): [-1.5  1.5 -1.5]
Median (rows): [ 1. -4.]
Std (flattened): 3.8622100754188224
Std (columns): [2.5 3.5 4.5]
Std (rows): [2.05480467 4.78423336]


In [ ]:
#(b) For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]). Find floor, ceiling
#and truncated value, rounded values
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])
print("Floor:", np.floor(a))
print("Ceil:", np.ceil(a))
print("Trunc:", np.trunc(a))
print("Rounded:", np.round(a))


Floor: [-2. -2. -1.  0.  1.  1.  3.]
Ceil: [-1. -1. -0.  1.  2.  2.  3.]
Trunc: [-1. -1. -0.  0.  1.  1.  3.]
Rounded: [-2. -2. -0.  0.  2.  2.  3.]


In [ ]:
#Q3: Based on Searching and Sorting
#(a) For the array: array = np.array([10, 52, 62, 16, 16, 54, 453]), find
#i. Sorted array
#ii. Indices of sorted array
#iii. 4 smallest elements
#iv. 5 largest elements 

array = np.array([10, 52, 62, 16, 16, 54, 453])

# Sorted
print("Sorted:", np.sort(array))
# Indices of sorted array
print("Indices of sorted:", np.argsort(array))
# 4 smallest
print("4 smallest:", np.partition(array, 3)[:4])
# 5 largest
print("5 largest:", np.partition(array, -5)[-5:])


Sorted: [ 10  16  16  52  54  62 453]
Indices of sorted: [0 3 4 1 5 2 6]
4 smallest: [16 10 16 52]
5 largest: [ 16  52  62  54 453]


In [ ]:
#(b) For the array: array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0]), find
#i. Integer elements only
#ii. Float elements only 
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

integers = array[np.floor(array) == array]
floats = array[np.floor(array) != array]
print("Integer elements:", integers)
print("Float elements:", floats)


Integer elements: [1. 2. 3. 2.]
Float elements: [1.2 2.2]


In [ ]:
#Q4:
#(a) Write a function named img_to_array(path) that reads an image from a specified path and
#save it as text file on local machine? (Note: use separate cases for RGB and Grey Scale
#images) 

from PIL import Image
import numpy as np

def img_to_array(path):
    img = Image.open(path)
    arr = np.array(img)
    if len(arr.shape) == 2:  # Grayscale
        np.savetxt("image_gray.txt", arr.astype(int), fmt='%d')
        print("Saved grayscale image to image_gray.txt")
    elif len(arr.shape) == 3:  # RGB
        # Save each channel as a separate file or combine into one file
        for i, color in enumerate(['R', 'G', 'B']):
            np.savetxt(f"image_{color}.txt", arr[:,:,i].astype(int), fmt='%d')
        print("Saved RGB image as image_R.txt, image_G.txt, image_B.txt")
    else:
        print("Unknown image format")

img_to_array('sample_image.jpg')


Saved RGB image as image_R.txt, image_G.txt, image_B.txt


In [ ]:
#(b) Load the saved file into jupyter notebook? 
# # For grayscale
# loaded_gray = np.loadtxt("image_gray.txt", dtype=int)
# print(loaded_gray)

# For RGB channel
loaded_R = np.loadtxt("image_R.txt", dtype=int)
loaded_G = np.loadtxt("image_G.txt", dtype=int)
loaded_B = np.loadtxt("image_B.txt", dtype=int)
# To stack into an RGB image again:
restored_img = np.stack([loaded_R, loaded_G, loaded_B], axis=-1)
print(restored_img)


[[[121 179 227]
  [121 179 227]
  [121 179 227]
  ...
  [194 226 247]
  [194 226 247]
  [194 226 247]]

 [[122 180 228]
  [122 180 228]
  [122 180 228]
  ...
  [195 227 248]
  [195 227 248]
  [195 227 248]]

 [[123 181 227]
  [123 181 227]
  [123 181 227]
  ...
  [195 227 248]
  [195 227 248]
  [195 227 248]]

 ...

 [[ 73  90  19]
  [ 69  85  20]
  [ 54  67  14]
  ...
  [212 238 237]
  [163 182 176]
  [221 227 215]]

 [[ 65  82  11]
  [ 69  85  22]
  [ 99 111  61]
  ...
  [191 224 231]
  [154 175 178]
  [206 217 213]]

 [[ 72  89  18]
  [100 116  53]
  [ 98 110  60]
  ...
  [182 221 238]
  [145 173 187]
  [199 213 224]]]
